#######################################
##                                   ##
##            Templates              ##
##                                   ##
#######################################

.module_tree_build:
    variables:
        -   PYTHON_PACKAGES: sympy numpy influxdb GitPython machinestate
    before_script:
        - JAVA_HOME=$HOME/jdk-11.0.14 ; export JAVA_HOME
        - SBT_HOME=$HOME/sbt ; export SBT_HOME
        - PATH=$JAVA_HOME/bin:$SBT_HOME/bin:$PATH ; export PATH
        - module load python/3.8-anaconda
        - |
            for PACKAGE in $PYTHON_PACKAGES
            do
                python3 -m pip install --user $PACKAGE
            done
    after_script:
        - |
            for PACKAGE in $PYTHON_PACKAGES
            do
                python3 -m pip uninstall $PACKAGE # cleanup
            done

.module_tree_run: &module_load_run
    - module load openmpi/4.1.1-gcc
    - mpirun --version
    - module load likwid/5.2.1
    - likwid-features --version

.module_tree_run_cuda: &module_load_run_cuda
    - module load module load cuda/11.4
    - nvcc --version
    - nvidia-smi
    - updatedb

.pfgen_template:
    tags:
        - testcluster
    artifacts:
        when: always
        paths:
            - Benchmark/Platform/$SLURM_NODELIST.platform
        expire_in: 1 weeks
    variables:
        SLURM_NODELIST: "TO_BE_REPLACED"
    before_script:
        - cd pfgen
    script:
        - !reference [ .module_tree_build, before_script ]
        - mkdir -p ../Benchmark/Platform
        - python3 -m pfgen --log=debug > ../Benchmark/Platform/$SLURM_NODELIST.platform
        - cd ..
    after_script:
        - !reference [ .module_tree_build, after_script ]

.bench_pipe_template:
    tags:
        - testcluster
    artifacts:
        when: on_failure
        paths:
            - Benchmark/output/Debug/*
            - Benchmark/output/generated/*
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
        COMPILER_PATH: "../Compiler/Compiler.jar"
        COMPILER_LIB_PATH: "../Compiler/lib"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"
        OUTPUT_PATH: "output"
    before_script:
        - cd Benchmark
        - !reference [ .module_tree_build, before_script ]
    script:
        - python3 slurm_alloc.py $EXA_PROBLEM_PATH $PLATFORM_PATH
        - *module_load_run
        - HOSTNAME=$(hostname)
        - python3 run_benchmark.py $COMPILER_PATH $COMPILER_LIB_PATH $EXA_PROBLEM_PATH $OUTPUT_PATH Platform/$HOSTNAME.platform --compile --run
    after_script:
        - !reference [ .module_tree_build, after_script ]