#######################################
##                                   ##
##            Templates              ##
##                                   ##
#######################################

.module_tree_build:
    variables:
        -   PYTHON_PACKAGES: sympy numpy influxdb GitPython machinestate
    before_script:
        - JAVA_HOME=$HOME/jdk-11.0.14 ; export JAVA_HOME
        - SBT_HOME=$HOME/sbt ; export SBT_HOME
        - PATH=$JAVA_HOME/bin:$SBT_HOME/bin:$PATH ; export PATH
        - module load python/3.8-anaconda
        - |
            for PACKAGE in $PYTHON_PACKAGES
            do
                python3 -m pip install --user $PACKAGE
            done
    after_script:
        - |
            for PACKAGE in $PYTHON_PACKAGES
            do
                python3 -m pip uninstall $PACKAGE # cleanup
            done

.module_mpi: &module_load_mpi
    - module load openmpi/4.1.1-gcc
    - mpirun --version

.module_likwid: &module_load_likwid
    - module load likwid/5.2.1
    - likwid-features --version

.module_cuda: &module_load_cuda
    - module load module load cuda/11.4
    - nvcc --version
    - nvidia-smi
    - updatedb

.bench_pipe_template:
    tags:
        - testcluster
    variables:
        NO_SLURM_SUBMIT: 1
        COMPILER_PATH: "../Compiler/Compiler.jar"
        COMPILER_LIB_PATH: "../Compiler/lib"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"
        OUTPUT_PATH: "output"
    before_script:
        - cd Benchmark
        - !reference [ .module_tree_build, before_script ]
        - 'curl -L --header "PRIVATE-TOKEN: $API_TOKEN" "https://gitlab.rrze.fau.de/api/v4/projects/ExaStencils%2Fpfgen/jobs/artifacts/master/download?job=collect-artifacts" --output artifacts.zip'
        - 'curl -L --header "PRIVATE-TOKEN: $API_TOKEN" "https://gitlab.rrze.fau.de/api/v4/projects/ExaStencils%2FExaStencils/jobs/artifacts/$CI_COMMIT_REF_NAME/download?job=bench_gen:$EXA_PROBLEM_NAME" --output output.zip'
        - unzip artifacts.zip -d Platform
        - unzip output.zip -d output
    script:
        - |
            if [[ ! -f "Platform/$HOSTNAME.platform" ]]; then
                echo "Skipping host without corresponding platform file"
                exit 0
            fi
        - echo "Found Platform/$HOSTNAME.platform"
        - python3 slurm_alloc.py $EXA_PROBLEM_PATH Platform/$HOSTNAME.platform
        - *module_load_mpi
        - *module_load_likwid
        - ls -al
        - python3 run_benchmark.py $COMPILER_PATH $COMPILER_LIB_PATH $EXA_PROBLEM_PATH $OUTPUT_PATH Platform/$HOSTNAME.platform --compile --run
    after_script:
        - !reference [ .module_tree_build, after_script ]