generate-docker-image:
    stage: build
    when: manual
    image: docker:latest
    tags:
        - docker-docker
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11 || true
        - docker build --pull . -f  dockerfiles/ubuntu-18.04-openjdk-11.Dockerfile -t i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
        - docker push i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11

build:generator:
    stage: build
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
    tags:
        - docker
    artifacts:
        paths:
            - Compiler/Compiler.jar
            - Compiler/lib
            - Examples
            - Testing
        expire_in: 1 weeks
    script:
        - java -version
        - sbt compile
        - sbt assembly

test:Tensor1_Constructors:
    stage: test
    dependencies:
        - build:generator
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
    tags:
        - docker
    artifacts:
        when: on_failure
        paths:
            - Testing/output/Debug/*
        expire_in: 1 weeks

    script:
        - java -version
        - python3 --version
        - mpirun --version
        - cd Testing
        - python3 run_test.py ../Compiler/Compiler.jar:../Compiler/lib Tensor1_Constructors TensorClass/Constructors/Tensor1_constructors.knowledge "TensorClass/Constructors/Tensor1_constructors.exa4" TensorClass/Constructors/Tensor1_constructors.results 1 1 Platform/random.platform output

test:Tensor2_Constructors:
    stage: test
    dependencies:
        - build:generator
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
    tags:
        - docker
    artifacts:
        when: on_failure
        paths:
            - Testing/output/Debug/*
        expire_in: 1 weeks

    script:
        - java -version
        - python3 --version
        - mpirun --version
        - cd Testing
        - python3 run_test.py ../Compiler/Compiler.jar:../Compiler/lib Tensor2_Constructors TensorClass/Constructors/Tensor2_constructors.knowledge "TensorClass/Constructors/Tensor2_constructors.exa4" TensorClass/Constructors/Tensor2_constructors.results 1 1 Platform/random.platform output

test:TensorN_Constructors:
    stage: test
    dependencies:
        - build:generator
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
    tags:
        - docker
    artifacts:
        when: on_failure
        paths:
            - Testing/output/Debug/*
        expire_in: 1 weeks

    script:
        - java -version
        - python3 --version
        - mpirun --version
        - cd Testing
        - python3 run_test.py ../Compiler/Compiler.jar:../Compiler/lib TensorN_Constructors TensorClass/Constructors/TensorN_constructors.knowledge "TensorClass/Constructors/TensorN_constructors.exa4" TensorClass/Constructors/TensorN_constructors.results 1 1 Platform/random.platform output

test:Tensor2_Arithmetic:
    stage: test
    dependencies:
        - build:generator
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
    tags:
        - docker
    artifacts:
        when: on_failure
        paths:
            - Testing/output/Debug/*
        expire_in: 1 weeks

    script:
        - java -version
        - python3 --version
        - mpirun --version
        - cd Testing
        - python3 run_test.py ../Compiler/Compiler.jar:../Compiler/lib Tensor2_Arithmetic TensorClass/Arithmetic/Tensor2_arithmetic.knowledge "TensorClass/Arithmetic/Tensor2_arithmetic.exa4" TensorClass/Arithmetic/Tensor2_arithmetic.results 1 1 Platform/random.platform output

