stages:
    - build
    - job_gen
    - benchmark

#######################################
##                                   ##
##         Templates                 ##
##                                   ##
#######################################

.module_tree:
    variables:
        - PYTHON_PACKAGES: sympy numpy influxdb GitPython
    before_script:
        - JAVA_HOME=$HOME/jdk-11.0.14 ; export JAVA_HOME
        - SBT_HOME=$HOME/sbt ; export SBT_HOME
        - PATH=$JAVA_HOME/bin:$SBT_HOME/bin:$PATH ; export PATH
        - module load python/3.8-anaconda
        - |
            for PACKAGE in $PYTHON_PACKAGES
            do
                python3 pip install --user $PACKAGE
            done
        - module load openmpi/4.1.1-gcc
        - module load likwid/5.2.1
    after_script:
        - |
            for PACKAGE in $PYTHON_PACKAGES
            do
                python3 pip uninstall $PACKAGE # cleanup
            done

.job_gen_template:
    stage: job_gen
    tags:
        - testcluster
    script:
        - chmod +x Benchmark/generate_jobs_for_hosts.sh
        - Benchmark/generate_jobs_for_hosts.sh $EXA_PROBLEM_NAME $EXA_PROBLEM_PATH > $EXA_PROBLEM_NAME-pipe.yml
    artifacts:
        paths:
            - $EXA_PROBLEM_NAME-pipe.yml
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"

.job_pipe_template:
    stage: benchmark
    trigger:
        include:
            artifact: $EXA_PROBLEM_NAME-pipe.yml
            job: job_gen:$EXA_PROBLEM_NAME
        strategy: depend
    variables:
        PARENT_PIPELINE_ID: $CI_PIPELINE_ID
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"


.benchmark_template:
    dependencies:
        - build:generator
    tags:
        - testcluster
    artifacts:
        when: on_failure
        paths:
            - Benchmark/output/Debug/*
            - Benchmark/output/generated/*
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
        COMPILER_PATH: "../Compiler/Compiler.jar"
        COMPILER_LIB_PATH: "../Compiler/lib"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"
        OUTPUT_PATH: "output"
        PLATFORM_PATH: "Platform/rome1.platform"
    before_script:
        - cd Benchmark
        - !reference [.module_tree, before_script]
    script:
        - python3 slurm_alloc.py $EXA_PROBLEM_PATH $PLATFORM_PATH
        - mpirun --version
        - python3 run_benchmark.py $COMPILER_PATH $COMPILER_LIB_PATH $EXA_PROBLEM_PATH $OUTPUT_PATH $PLATFORM_PATH
    after_script:
        - !reference [.module_tree, after_script]

.benchmark_template_CUDA:
    extends: .benchmark_template
    script:
        - python3 slurm_alloc.py $EXA_PROBLEM_PATH $PLATFORM_PATH
        - mpirun --version
        - module load cuda/11.4
        - nvcc --version
        - nvidia-smi
        - updatedb
        - python3 run_benchmark.py $COMPILER_PATH $COMPILER_LIB_PATH $EXA_PROBLEM_PATH $OUTPUT_PATH $PLATFORM_PATH

#######################################
##                                   ##
##         Generator                 ##
##                                   ##
#######################################

build:generator:
    stage: build
    tags:
        - testcluster
    artifacts:
        paths:
            - Compiler/Compiler.jar
            - Compiler/lib
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
    before_script:
        - !reference [ .module_tree, before_script ]
        - sbt sbtVersion
        - java -version
        - python3 --version
    script:
        - sbt compile
        - sbt assembly
    after_script:
        - !reference [ .module_tree, after_script ]

#######################################
##                                   ##
##       Benchmark Generation        ##
##                                   ##
#######################################

job_gen:5pt_Jac_2D:
    extends: .job_gen_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"

#######################################
##                                   ##
##       Benchmark Execution         ##
##                                   ##
#######################################

benchmark:5pt_Jac_2D:
    extends: .job_pipe_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"
