docker-ubuntu:
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker pull i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8 || true
     - docker build --pull . -f dockerfiles/ubuntu-18.04-openjdk-8.Dockerfile -t i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8
     - docker push i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8
   image: docker:latest
   when: manual
   tags:
      - docker-docker

test-examples:
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8 
    variables:
        PLATFORM: Platform/random.platform
    script:
        - java -version
        - python3 --version
        - mpirun --version
        - git clone https://github.com/stganser/isl.git
        - cd isl
        - mkdir install
        - export ISL_INSTALL="${PWD}/install"
        - ./autogen.sh
        - ./configure --prefix=${ISL_INSTALL} --with-jni-include=/usr/lib/jvm/java-8-openjdk-amd64/include --with-clang=system
        - cd ..
        - sbt compile
        - sbt assembly
        - cd Testing
        - python3 run_test.py 2D_FD_Poisson_fromL1  Main  Poisson/2D_FD_Poisson_fromL1.knowledge  "../Examples/Poisson/2D_FD_Poisson_fromL1.exa1"  Poisson/2D_FD_Poisson_fromL1.results  4   4    $PLATFORM
        - python3 run_test.py 2D_FD_Poisson_fromL2  Main  Poisson/2D_FD_Poisson_fromL2.knowledge  "../Examples/Poisson/2D_FD_Poisson_fromL2.exa2;../Examples/Poisson/2D_FD_Poisson_fromL2.exa3;../Examples/Poisson/2D_FD_Poisson_fromL2.exa4"  Poisson/2D_FD_Poisson_fromL2.results  4   4    $PLATFORM
        - python3 run_test.py 2D_FD_Poisson_fromL3  Main  Poisson/2D_FD_Poisson_fromL3.knowledge  "../Examples/Poisson/2D_FD_Poisson_fromL3.exa3;../Examples/Poisson/2D_FD_Poisson_fromL3.exa4"  Poisson/2D_FD_Poisson_fromL3.results  4   4  $PLATFORM
        - python3 run_test.py 2D_FD_Poisson_fromL4  Main  Poisson/2D_FD_Poisson_fromL4.knowledge  "../Examples/Poisson/2D_FD_Poisson_fromL4.exa4"  Poisson/2D_FD_Poisson_fromL4.results  4   4    $PLATFORM
        - python3 run_test.py 2D_FV_Poisson_fromL2  Main  Poisson/2D_FV_Poisson_fromL2.knowledge  "../Examples/Poisson/2D_FV_Poisson_fromL2.exa2;../Examples/Poisson/2D_FV_Poisson_fromL2.exa3;../Examples/Poisson/2D_FV_Poisson_fromL2.exa4"  Poisson/2D_FV_Poisson_fromL2.results  4   4    $PLATFORM 
        - python3 run_test.py 2D_FV_Poisson_fromL4  Main  Poisson/2D_FV_Poisson_fromL4.knowledge  "../Examples/Poisson/2D_FV_Poisson_fromL4.exa4"  Poisson/2D_FV_Poisson_fromL4.results  4   4    $PLATFORM
        - python3 run_test.py 2D_FE_Poisson_fromL2  Main  Poisson/2D_FE_Poisson_fromL2.knowledge  "../Examples/Poisson/2D_FE_Poisson_fromL2.exa2;../Examples/Poisson/2D_FE_Poisson_fromL2.exa3;../Examples/Poisson/2D_FE_Poisson_fromL2.exa4"  Poisson/2D_FE_Poisson_fromL2.results  1   1    $PLATFORM
    tags:
        - docker
        - cuda
        - AVX
    artifacts:
        when: on_failure
        paths:
            - Testing/output/Debug/*
        expire_in: 1 weeks




