docker-ubuntu:
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker pull i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8 || true
     - docker build --pull . -f dockerfiles/ubuntu-18.04-openjdk-8.Dockerfile -t i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8
     - docker push i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8
   image: docker:latest
   when: manual
   tags:
      - docker-docker

test-ubuntu:
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8 
    script:
        - sbt compile
        - sbt assembly
        - cd Testing
        - python run_test.py 2D_FD_Poisson_fromL1 Main Poisson/2D_FD_Poisson_fromL1.knowledge ../Examples/Poisson/2D_FD_Poisson_fromL1.exa1 Poisson/2D_FD_Poisson_fromL1.results 4 4 Platform/random.platform
    tags:
        - docker
