variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - stage_gen
    - stage_pipe
    - bench_gen
    - bench_pipe

include: 'Benchmark/.benchmark_templates.yml'

#######################################
##                                   ##
##         Generator                 ##
##                                   ##
#######################################

build:generator:
    stage: build
    tags:
        - testcluster
    artifacts:
        paths:
            - Compiler/Compiler.jar
            - Compiler/lib
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
    before_script:
        - !reference [ .module_tree_build, before_script ]
        - sbt sbtVersion
        - java -version
        - python3 --version
    script:
        - sbt compile
        - sbt assembly
    after_script:
        - !reference [ .module_tree_build, after_script ]

###################################
##                               ##
##       Stage Generation        ##
##                               ##
###################################

# 5-pt stencil

stage_gen:5pt_Jac_2D:
    extends: .gen_stages_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"
        EXASLANG_FILES: "5pt_Jac_Cell.exa4"
        KNOWLEDGE_FILE: "5pt_Jac_Cell.knowledge"

# 3D FD Poisson

stage_gen:3D_FD_Poisson:
    extends: .gen_stages_template
    variables:
        EXA_PROBLEM_NAME: "3D_FD_Poisson"
        EXA_PROBLEM_PATH: "Poisson3D"
        EXASLANG_FILES: "3D_FD_Poisson_fromL4.exa4"
        KNOWLEDGE_FILE: "3D_FD_Poisson_fromL4.knowledge"

###################################
##                               ##
##       Stage Execution         ##
##                               ##
###################################

# 5-pt stencil

stage_pipe:5pt_Jac_2D:
    extends: .pipe_stage_job_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"

# 3D FD Poisson

stage_pipe:3D_FD_Poisson:
    extends: .pipe_stage_job_template
    variables:
        EXA_PROBLEM_NAME: "3D_FD_Poisson"
