stages:
    - .pre
    - pf_gen
    - build
    - job_gen
    - benchmark

include: 'Benchmark/.benchmark_templates.yml'

#######################################
##                                   ##
##            Templates              ##
##                                   ##
#######################################

.gen_bench_job_template:
    dependencies:
        - build:generator
    stage: job_gen
    tags:
        - testcluster
    before_script:
        - cd Benchmark
        - !reference [ .module_tree_build, before_script ]
    script:
        - |
            for pf in /Platform/*.platform
            do
                python3 run_benchmark.py $COMPILER_PATH $COMPILER_LIB_PATH $EXA_PROBLEM_PATH $OUTPUT_PATH $pf --generate
            done
        - chmod +x generate_bench_jobs_for_hosts.sh
        - ./generate_bench_jobs_for_hosts.sh $EXA_PROBLEM_NAME $EXA_PROBLEM_PATH > $EXA_PROBLEM_NAME-pipe.yml
    after_script:
        - !reference [ .module_tree_build, after_script ]
    artifacts:
        paths:
            - $EXA_PROBLEM_NAME-pipe.yml
            - $OUTPUT_PATH/generated
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
        COMPILER_PATH: "../Compiler/Compiler.jar"
        COMPILER_LIB_PATH: "../Compiler/lib"
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"

.pipe_bench_job_template:
    stage: benchmark
    trigger:
        include:
            artifact: $EXA_PROBLEM_NAME-pipe.yml
            job: job_gen:$EXA_PROBLEM_NAME
        strategy: depend
    needs:
        pipeline: $PARENT_PIPELINE_ID
    variables:
        PARENT_PIPELINE_ID: $CI_PIPELINE_ID
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"

#######################################
##                                   ##
##       Platform Generation         ##
##                                   ##
#######################################

pf_gen:gen_pf_job:
    stage: pf_gen
    tags:
        - testcluster
    before_script:
        - cd Benchmark
    script:
        - chmod +x generate_pf_jobs_for_hosts.sh
        - ./generate_pf_jobs_for_hosts.sh > gen-platform-pipe.yml
    artifacts:
        paths:
            - gen-platform-pipe.yml
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1

pf_gen:pipe_pf_job:
    stage: pf_gen
    trigger:
        include:
            artifact: gen-platform-pipe.yml
            job: pf_gen:gen_pf_job
        strategy: depend
    needs:
        pipeline: $PARENT_PIPELINE_ID
    variables:
        PARENT_PIPELINE_ID: $CI_PIPELINE_ID

#######################################
##                                   ##
##         Generator                 ##
##                                   ##
#######################################

build:generator:
    stage: build
    tags:
        - testcluster
    artifacts:
        paths:
            - Compiler/Compiler.jar
            - Compiler/lib
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
    before_script:
        - !reference [ .module_tree_build, before_script ]
        - sbt sbtVersion
        - java -version
        - python3 --version
    script:
        - sbt compile
        - sbt assembly
    after_script:
        - !reference [ .module_tree_build, after_script ]

#######################################
##                                   ##
##       Benchmark Generation        ##
##                                   ##
#######################################

job_gen:5pt_Jac_2D:
    extends: .gen_bench_job_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"

#######################################
##                                   ##
##       Benchmark Execution         ##
##                                   ##
#######################################

benchmark:5pt_Jac_2D:
    extends: .pipe_bench_job_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"
