stages:
    - build
    - job_gen
    - benchmark

include: 'Benchmark/.benchmark_templates.yml'

#######################################
##                                   ##
##            Templates              ##
##                                   ##
#######################################

.job_gen_template:
    dependencies:
        - build:generator
    stage: job_gen
    tags:
        - testcluster
    script:
        - chmod +x Benchmark/generate_jobs_for_hosts.sh
        - Benchmark/generate_jobs_for_hosts.sh $EXA_PROBLEM_NAME $EXA_PROBLEM_PATH > $EXA_PROBLEM_NAME-pipe.yml
    artifacts:
        paths:
            - $EXA_PROBLEM_NAME-pipe.yml
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"

.job_pipe_template:
    stage: benchmark
    trigger:
        include:
            artifact: $EXA_PROBLEM_NAME-pipe.yml
            job: job_gen:$EXA_PROBLEM_NAME
        strategy: depend
    variables:
        PARENT_PIPELINE_ID: $CI_PIPELINE_ID
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"

#######################################
##                                   ##
##         Generator                 ##
##                                   ##
#######################################

build:generator:
    stage: build
    tags:
        - testcluster
    artifacts:
        paths:
            - Compiler/Compiler.jar
            - Compiler/lib
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
    before_script:
        - !reference [ .module_tree_build, before_script ]
        - sbt sbtVersion
        - java -version
        - python3 --version
    script:
        - sbt compile
        - sbt assembly
    after_script:
        - !reference [ .module_tree_build, after_script ]

#######################################
##                                   ##
##       Benchmark Generation        ##
##                                   ##
#######################################

job_gen:5pt_Jac_2D:
    extends: .job_gen_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"

#######################################
##                                   ##
##       Benchmark Execution         ##
##                                   ##
#######################################

benchmark:5pt_Jac_2D:
    extends: .job_pipe_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"
