docker-ubuntu:
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker pull i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8 || true
     - docker build --pull . -f dockerfiles/ubuntu-18.04-openjdk-8.Dockerfile -t i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8
     - docker push i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8
   image: docker:latest
   when: manual
   tags:
      - docker-docker

test-ubuntu:
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-8 
    script:
        - git clone https://github.com/stganser/isl.git
        - cd isl
        - mkdir install
        - export ISL_INSTALL="${PWD}/install"
        - ./autogen.sh
        - ./configure --prefix=${ISL_INSTALL} --with-jni-include=/usr/lib/jvm/default-java/include/ --with-clang=system
        - cd interface
        - cd ${BASE_DIR}/isl/interface
        - make isl-scala.jar
        - cp -r java/gen src
        - cp scala/src/isl/Conversions.scala src/isl
        - zip -r isl-scala.jar src
        - cd ..
        - mkdir libs
        - cp isl/src/* libs
        - sbt compile
        - sbt assembly
        - cd Testing
        - python3 run_test.py ExaStokes_2D tmp ../Compiler/Compiler.jar Application/ExaStokes_2D.knowledge Platform/random.platform Application/ExaStokes_2D.exa4 Application/ExaStokes_2D.results
    tags:
        - docker
