variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - pf_gen
    - bench_gen
    - bench_pipe

include: 'Benchmark/.benchmark_templates.yml'

#######################################
##                                   ##
##            Templates              ##
##                                   ##
#######################################

.gen_bench_job_template:
    dependencies:
        - build:generator
    stage: bench_gen
    tags:
        - testcluster
    before_script:
        - cd Benchmark
        - !reference [ .module_tree_build, before_script ]
    script:
        - |
            for pf in Platform/*.platform
            do
                python3 run_benchmark.py $COMPILER_PATH $COMPILER_LIB_PATH $EXA_PROBLEM_PATH $OUTPUT_PATH $pf --generate
            done
        - chmod +x generate_bench_jobs_for_hosts.sh
        - ./generate_bench_jobs_for_hosts.sh $EXA_PROBLEM_NAME $EXA_PROBLEM_PATH > $EXA_PROBLEM_NAME-pipe.yml
    after_script:
        - !reference [ .module_tree_build, after_script ]
    artifacts:
        paths:
            - $EXA_PROBLEM_NAME-pipe.yml
            - $OUTPUT_PATH/generated
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
        COMPILER_PATH: "../Compiler/Compiler.jar"
        COMPILER_LIB_PATH: "../Compiler/lib"
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"

.pipe_bench_job_template:
    stage: bench_pipe
    trigger:
        include:
            artifact: $EXA_PROBLEM_NAME-pipe.yml
            job: job_gen:$EXA_PROBLEM_NAME
        strategy: depend
    needs:
        pipeline: $PARENT_PIPELINE_ID
    variables:
        PARENT_PIPELINE_ID: $CI_PIPELINE_ID
        EXA_PROBLEM_NAME: "TO_BE_REPLACED"
        EXA_PROBLEM_PATH: "TO_BE_REPLACED"

#######################################
##                                   ##
##         Generator                 ##
##                                   ##
#######################################

build:generator:
    stage: build
    tags:
        - testcluster
    artifacts:
        paths:
            - Compiler/Compiler.jar
            - Compiler/lib
        expire_in: 1 weeks
    variables:
        NO_SLURM_SUBMIT: 1
    before_script:
        - !reference [ .module_tree_build, before_script ]
        - sbt sbtVersion
        - java -version
        - python3 --version
    script:
        - sbt compile
        - sbt assembly
    after_script:
        - !reference [ .module_tree_build, after_script ]

#######################################
##                                   ##
##       Platform Generation         ##
##                                   ##
#######################################

pf_gen:broadep2:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "broadep2"

pf_gen:hasep1:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "hasep1"

pf_gen:interlagos1:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "interlagos1"

pf_gen:ivyep1:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "ivyep1"

pf_gen:casclakesp2:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "casclakesp2"

pf_gen:icx36:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "icx36"

pf_gen:medusa:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "medusa"

pf_gen:milan1:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "milan1"

pf_gen:naples1:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "naples1"

pf_gen:optane1:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "optane1"

pf_gen:phinally:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "phinally"

pf_gen:rome1:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "rome1"

pf_gen:rome2:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "rome2"

pf_gen:skylakesp2:
    extends: .pfgen_template
    stage: pf_gen
    variables:
        SLURM_NODELIST: "skylakesp2"

#######################################
##                                   ##
##       Benchmark Generation        ##
##                                   ##
#######################################

bench_gen:5pt_Jac_2D:
    extends: .gen_bench_job_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"

#######################################
##                                   ##
##       Benchmark Execution         ##
##                                   ##
#######################################

bench_pipe:5pt_Jac_2D:
    extends: .pipe_bench_job_template
    variables:
        EXA_PROBLEM_NAME: "5pt_Jac_2D"
        EXA_PROBLEM_PATH: "FivePointStencil"
