variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - pipeline

pipeline_gen:
    stage: pipeline
    tags:
        - testcluster
    before_script:
        - cd Benchmark
    script:
        - echo 'hello'
