generate-docker-image:
    stage: build
    when: manual
    image: docker:latest
    tags:
        - docker-docker
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11 || true
        - docker build --pull . -f  dockerfiles/ubuntu-18.04-openjdk-11.Dockerfile -t i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
        - docker push i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11

build:generator:
    stage: build
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
    tags:
        - docker
    artifacts:
        paths:
            - Compiler/Compiler.jar
            - Compiler/lib
            - Examples
            - Testing
        expire_in: 1 weeks
    script:
        - java -version
        - sbt compile
        - sbt assembly

test:TensorAccess:
    stage: test
    dependencies:
        - build:generator
    image: i10git.cs.fau.de:5005/exastencils/exastencils/ubuntu-18.04-openjdk-11
    tags:
        - docker
    artifacts:
        when: on_failure
        paths:
            - Testing/output/Debug/*
        expire_in: 1 weeks

    script:
        - java -version
        - python3 --version
        - mpirun --version
        - cd Testing
        - python3 run_test.py ../Compiler/Compiler.jar:../Compiler/lib TensorAccess Tensor/Tensor_test.knowledge "Tensor/Tensor_test.exa4" Tensor/Tensor_test.results 1 1 Platform/random.platform output

