package exastencils.knowledge.l2

import exastencils.util.StrategyContainer

object L2_UnfoldLeveledDeclarations extends StrategyContainer

object L2_PrepareDeclarations extends StrategyContainer

object L2_PrepareAccesses extends StrategyContainer

object L2_ProcessDeclarations extends StrategyContainer

object L2_ResolveAccesses extends StrategyContainer
