python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_ExaStokes_2D Application/ExaStokes_2D.knowledge "Application/ExaStokes_2D.exa4" Application/ExaStokes_2D.results 1 10 Platform/random.platform output
python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_ExaStokes_3D Application/ExaStokes_3D.knowledge "Application/ExaStokes_3D.exa4" Application/ExaStokes_3D.results 1 10 Platform/random.platform output
python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_ExaFluids Application/ExaFluids.knowledge "Application/ExaFluids.exa4" Application/ExaFluids.results 1 10 Platform/random.platform output
python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_ExaFluids_PowerLaw Application/ExaFluids.knowledge "Application/ExaFluids_PowerLaw.exa4" Application/ExaFluids_PowerLaw.results 1 10 Platform/random.platform output
 python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_ExaFluids_Bingham Application/ExaFluids.knowledge "Application/ExaFluids_Bingham.exa4" Application/ExaFluids_Bingham.results 1 10 Platform/random.platform output
  python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_ExaFluids_Par Application/ExaFluids_Parallel.knowledge "Application/ExaFluids.exa4" Application/ExaFluids_Parallel.results 4 2 Platform/random.platform output
  python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_OptFlow2D Application/OpticalFlow2D.knowledge "Application/OpticalFlow2D.exa4" Application/OpticalFlow2D.results 1 10 Platform/random.platform output
  python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar Appl_OptFlow3D Application/OpticalFlow3D.knowledge "Application/OpticalFlow3D.exa4" Application/OpticalFlow3D.results 1 10 Platform/random.platform output
  python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar P#ar_TestF_vectSAlAl Opts/par__float_vectAlAl.knowledge "Opts/base_par_flt.exa4" Opts/par__float.results 8 4 Platform/random.platform output
   python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar 2D_FD_Poisson_fromL1 Poisson/2D_FD_Poisson_fromL1.knowledge "../Examples/Poisson/2D_FD_Poisson_fromL1.exa1" Poisson/2D_FD_Poisson_fromL1.results 4 4 Platform/random.platform output
    python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar 2D_FD_Poisson_fromL2 Poisson/2D_FD_Poisson_fromL2.knowledge "../Examples/Poisson/2D_FD_Poisson_fromL2.exa2;../Examples/Poisson/2D_FD_Poisson_fromL2.exa3;../Examples/Poisson/2D_FD_Poisson_fromL2.exa4" Poisson/2D_FD_Poisson_fromL2.results 4 4 Platform/random.platform output
    python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar 2D_FD_Poisson_fromL3 Poisson/2D_FD_Poisson_fromL3.knowledge "../Examples/Poisson/2D_FD_Poisson_fromL3.exa3;../Examples/Poisson/2D_FD_Poisson_fromL3.exa4" Poisson/2D_FD_Poisson_fromL3.results 4 4 Platform/random.platform output
     python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar 2D_FD_Poisson_fromL4 Poisson/2D_FD_Poisson_fromL4.knowledge "../Examples/Poisson/2D_FD_Poisson_fromL4.exa4" Poisson/2D_FD_Poisson_fromL4.results 4 4 Platform/random.platform output
      python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar 2D_FV_Poisson_fromL2 Poisson/2D_FV_Poisson_fromL2.knowledge "../Examples/Poisson/2D_FV_Poisson_fromL2.exa2;../Examples/Poisson/2D_FV_Poisson_fromL2.exa3;../Examples/Poisson/2D_FV_Poisson_fromL2.exa4" Poisson/2D_FV_Poisson_fromL2.results 4 4 Platform/random.platform output
      python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar 2D_FV_Poisson_fromL4 Poisson/2D_FV_Poisson_fromL4.knowledge "../Examples/Poisson/2D_FV_Poisson_fromL4.exa4" Poisson/2D_FV_Poisson_fromL4.results 4 4 Platform/random.platform output
      python3 run_test.py ../classes/artifacts/Compiler_jar/Compiler.jar 2D_FE_Poisson_fromL2 Poisson/2D_FE_Poisson_fromL2.knowledge "../Examples/Poisson/2D_FE_Poisson_fromL2.exa2;../Examples/Poisson/2D_FE_Poisson_fromL2.exa3;../Examples/Poisson/2D_FE_Poisson_fromL2.exa4" Poisson/2D_FE_Poisson_fromL2.results 1 1 Platform/random.platform output
      