name: Build ExaStencils Code Generator

on:
  push:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests
        run: sbt test
      - name: Build compiler
        run: java -version; sbt compile; sbt assembly
      - name: Upload compiler artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Compiler.jar
          path: Compiler/Compiler.jar
