name: Build ExaStencils Code Generator

on:
  push:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests
        run: sbt test
      - name: Build compiler
        run: java -version; sbt compile; sbt assembly
      - name: Upload compiler artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Compiler.jar
          path: Compiler/Compiler.jar

  page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel \
          pip install sphinx sphinx-rtd-theme \
      - name: Build page
        run: |
          mkdir public \
          sphinx-build docs public -b dirhtml \
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

